const zh = {
  title: '工作台扩展',
  marketplace: '插件市场',
  installed: '已安装',
  marketplaceEmpty: '插件市场尚未开放',
  marketplaceDescription: '目前可以安装本地插件包，为工作台添加命令与视图。',
  emptyDescription: '描述你的想法，让 Lexora 生成插件；也可以安装已有插件包。',
  more: '更多操作',
  description: '为工作台添加命令与视图。',
  install: '安装插件包',
  create: '生成插件',
  creationPrompt: '打字时，在当前分屏放礼花',
  creatorUnavailable: '插件创作技能不可用，请在技能设置中启用 plugin-creator。',
  acquisitionOptions: '更多插件获取方式',
  development: '加载开发目录',
  empty: '还没有安装工作台扩展',
  permissions: '申请的权限',
  selected: '读取通过命令选中的文件',
  network: '访问网站',
  notifications: '发送系统通知',
  schedules: '在 Lexora 运行期间执行后台定时任务',
  none: '不申请额外权限',
  cancel: '取消',
  confirm: '确认安装',
  version: '版本',
  pending: '待应用版本',
  restart: '重启扩展',
  enable: '启用',
  disable: '禁用',
  remove: '卸载',
  removeAndClear: '卸载并清理',
  cleanupHint: '“卸载并清理”还会永久删除插件设置、私有数据和视图状态，无法撤销。任务内容和用户文件不受影响。',
  removeTitle: '卸载扩展？',
  retained: '普通卸载会保留插件设置、私有数据和视图位置，重新安装后可继续使用。',
  diagnostics: '运行诊断',
  loading: '正在加载扩展…',
  failed: '扩展视图暂时不可用',
  retry: '重新启动',
  dependencies: '依赖',
  active: '运行中',
  inactive: '按需启动',
  activating: '正在启动',
  disabled: '已禁用',
  blocked: '依赖或版本不兼容',
  failedState: '运行失败',
  activation: '启动耗时',
  noLogs: '尚无运行记录',
  update: '安装更新',
  noAdded: '没有新增权限',
  installFailed: '操作未完成',
  error: '错误代码',
}
const en: typeof zh = {
  title: 'Workbench extensions',
  marketplace: 'Marketplace',
  installed: 'Installed',
  marketplaceEmpty: 'The marketplace is not available yet',
  marketplaceDescription: 'Install local plugin packages to add commands and views to your workbench.',
  emptyDescription: 'Describe your idea to generate a plugin with Lexora, or install an existing package.',
  more: 'More actions',
  description: 'Add commands and views to your workbench.',
  install: 'Install package',
  create: 'Generate plugin',
  creationPrompt: 'Show confetti in the current pane while I type',
  creatorUnavailable: 'The plugin creation skill is unavailable. Enable plugin-creator in Skills settings.',
  acquisitionOptions: 'More ways to add plugins',
  development: 'Load development folder',
  empty: 'No workbench extensions installed',
  permissions: 'Requested permissions',
  selected: 'Read files selected through commands',
  network: 'Access website',
  notifications: 'Show system notifications',
  schedules: 'Run scheduled commands while Lexora is running',
  none: 'No additional permissions',
  cancel: 'Cancel',
  confirm: 'Confirm installation',
  version: 'Version',
  pending: 'Pending version',
  restart: 'Restart extension',
  enable: 'Enable',
  disable: 'Disable',
  remove: 'Uninstall',
  removeAndClear: 'Uninstall and clear data',
  cleanupHint: '“Uninstall and clear data” also permanently deletes plugin settings, private data and view state. This cannot be undone. Tasks and user files are not affected.',
  removeTitle: 'Uninstall extension?',
  retained: 'Regular uninstall retains plugin settings, private data and view positions for reinstallation.',
  diagnostics: 'Runtime diagnostics',
  loading: 'Loading extension…',
  failed: 'This extension view is unavailable',
  retry: 'Restart',
  dependencies: 'Dependencies',
  active: 'Running',
  inactive: 'On demand',
  activating: 'Starting',
  disabled: 'Disabled',
  blocked: 'Dependency or version incompatible',
  failedState: 'Failed',
  activation: 'Activation time',
  noLogs: 'No runtime events yet',
  update: 'Install update',
  noAdded: 'No additional permissions',
  installFailed: 'The operation did not complete',
  error: 'Error code',
}
export function extensionLabels(language: string) {
  return language === 'en-US' ? en : zh
}
