import type { PresetWind3Theme } from 'unocss'

export const additionalThemeColors = [
  'app-sidebar-fg',
  'workspace-sidebar-fg',
  'reading',
  'reading-fg',
  'composer',
  'composer-fg',
  'hover-fg',
  'selected-fg',
  'pressed-fg',
  'link',
  'quote',
  'quote-border',
  'inline-code',
  'inline-code-fg',
  'code',
  'code-fg',
  'table-header',
  'table-border',
  'diff-added',
  'diff-removed',
  'editor',
  'editor-fg',
  'editor-line',
  'editor-gutter',
  'editor-cursor',
  'syntax-comment',
  'syntax-keyword',
  'syntax-string',
  'syntax-number',
  'syntax-function',
  'syntax-type',
  'syntax-variable',
  'syntax-operator',
  'terminal-background',
  'terminal-foreground',
  'terminal-muted',
  'terminal-scrollbar',
  'terminal-mauve',
  'terminal-blue',
  'terminal-green',
  'terminal-yellow',
  'terminal-peach',
  'terminal-maroon',
  'terminal-sky',
  'terminal-rosewater',
] as const

export const semanticColorTokens = {
  ...Object.fromEntries(additionalThemeColors.map(name => [name, `--buddy-${name}`])) as Record<typeof additionalThemeColors[number], string>,
  'canvas': '--buddy-surface-canvas',
  'app-sidebar': '--buddy-surface-app-sidebar',
  'workspace-sidebar': '--buddy-surface-workspace-sidebar',
  'surface': '--buddy-surface-base',
  'raised': '--buddy-surface-raised',
  'subtle': '--buddy-surface-subtle',
  'user-message': '--buddy-user-message-surface',
  'hover': '--buddy-state-hover',
  'pressed': '--buddy-state-pressed',
  'selected': '--buddy-state-selected',
  'selected-hover': '--buddy-state-selected-hover',
  'nav-hover': '--buddy-nav-hover',
  'nav-selected': '--buddy-nav-selected',
  'nav-selected-hover': '--buddy-nav-selected-hover',
  'nav-pressed': '--buddy-nav-pressed',
  'nav-foreground': '--buddy-nav-foreground',
  'border': '--buddy-border-subtle',
  'border-strong': '--buddy-border-strong',
  'strong': '--buddy-text-strong',
  'fg': '--buddy-text-primary',
  'muted': '--buddy-text-secondary',
  'disabled': '--buddy-text-disabled',
  'on-accent': '--buddy-text-on-accent',
  'accent': '--buddy-accent-solid',
  'accent-hover': '--buddy-accent-solid-hover',
  'accent-pressed': '--buddy-accent-solid-pressed',
  'accent-text': '--buddy-accent-text',
  'focus': '--buddy-focus-ring',
  'text-selection': '--buddy-text-selection',
  'text-selection-inactive': '--buddy-text-selection-inactive',
  'text-selection-match': '--buddy-text-selection-match',
  'accent-subtle': '--buddy-accent-surface-subtle',
  'accent-surface': '--buddy-accent-surface',
  'accent-surface-hover': '--buddy-accent-surface-hover',
  'accent-surface-pressed': '--buddy-accent-surface-pressed',
  'accent-border': '--buddy-accent-border',
  'accent-border-hover': '--buddy-accent-border-hover',
  'accent-on-surface': '--buddy-accent-on-surface',
  'success': '--buddy-status-success-text',
  'success-solid': '--buddy-status-success-solid',
  'success-surface': '--buddy-status-success-surface',
  'success-surface-hover': '--buddy-status-success-surface-hover',
  'success-border': '--buddy-status-success-border',
  'warning': '--buddy-status-warning-text',
  'warning-solid': '--buddy-status-warning-solid',
  'warning-surface': '--buddy-status-warning-surface',
  'warning-surface-hover': '--buddy-status-warning-surface-hover',
  'warning-border': '--buddy-status-warning-border',
  'danger': '--buddy-status-danger-text',
  'danger-solid': '--buddy-status-danger-solid',
  'danger-surface': '--buddy-status-danger-surface',
  'danger-surface-hover': '--buddy-status-danger-surface-hover',
  'danger-border': '--buddy-status-danger-border',
  'gold': '--buddy-brand-gold',
  'gold-surface': '--buddy-brand-gold-surface',
  'avatar': '--buddy-avatar-background',
  'avatar-foreground': '--buddy-avatar-foreground',
  'data-violet': '--buddy-data-violet',
  'data-cyan': '--buddy-data-cyan',
  'data-blue': '--buddy-data-blue',
} as const

export const themeFonts = {
  ui: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", "Noto Sans CJK SC", "Source Han Sans SC", "Microsoft YaHei", sans-serif',
  mono: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace',
} as const

export function createUnoTheme(namespace: 'buddy' | 'lexora'): PresetWind3Theme {
  return {
    colors: Object.fromEntries(Object.entries(semanticColorTokens).map(([name, token]) => [
      name,
      `var(${namespace === 'buddy' ? token : `--lexora-${name === 'accent' ? 'accent-solid' : name}`})`,
    ])),
    fontFamily: {
      sans: `var(--${namespace}-font-ui)`,
      mono: `var(--${namespace}-font-mono)`,
    },
    borderRadius: { micro: `var(--${namespace}-radius-micro)` },
  }
}

export function createExtensionThemeColors(variables: Record<string, string>): Record<string, string> {
  return {
    ...Object.fromEntries(Object.entries(semanticColorTokens).map(([name, token]) => [name, variables[token]!])),
    'background': variables['--buddy-surface-base']!,
    'text': variables['--buddy-text-primary']!,
    'accent': variables['--buddy-nav-foreground']!,
    'accent-solid': variables['--buddy-accent-solid']!,
    'font-ui': themeFonts.ui,
    'font-mono': themeFonts.mono,
    'radius-micro': '6px',
  }
}
