import type { BuddyColorTheme } from '@buddy-shared/theme/buddyTheme'
import type { GlobalThemeOverrides } from 'naive-ui'

export function createBuddyNaiveThemeOverrides(theme: BuddyColorTheme): GlobalThemeOverrides {
  const { accent, state } = theme
  return {
    Button: {
      colorHover: state.hover,
      colorPressed: state.pressed,
      colorFocus: state.hover,
      textColorHover: accent.text,
      textColorPressed: accent.onSurface,
      textColorFocus: accent.text,
      textColorTextHover: accent.text,
      textColorTextPressed: accent.text,
      textColorTextFocus: accent.text,
      textColorGhostHover: accent.text,
      textColorGhostPressed: accent.text,
      textColorGhostFocus: accent.text,
      textColorTextPrimary: accent.text,
      textColorTextHoverPrimary: accent.text,
      textColorTextPressedPrimary: accent.text,
      textColorTextFocusPrimary: accent.text,
      textColorGhostPrimary: accent.text,
      textColorGhostHoverPrimary: accent.text,
      textColorGhostPressedPrimary: accent.text,
      textColorGhostFocusPrimary: accent.text,
      textColorTextInfo: accent.text,
      textColorTextHoverInfo: accent.text,
      textColorTextPressedInfo: accent.text,
      textColorTextFocusInfo: accent.text,
      textColorGhostInfo: accent.text,
      textColorGhostHoverInfo: accent.text,
      textColorGhostPressedInfo: accent.text,
      textColorGhostFocusInfo: accent.text,
      borderHover: `1px solid ${accent.borderHover}`,
      borderPressed: `1px solid ${accent.focus}`,
      borderFocus: `1px solid ${accent.focus}`,
    },
    Input: {
      caretColor: accent.text,
      borderHover: `1px solid ${accent.borderHover}`,
      borderFocus: `1px solid ${accent.focus}`,
      boxShadowFocus: `0 0 0 2px ${state.selected}`,
    },
    InternalSelection: {
      caretColor: accent.text,
      borderHover: `1px solid ${accent.borderHover}`,
      borderActive: `1px solid ${accent.focus}`,
      borderFocus: `1px solid ${accent.focus}`,
      boxShadowActive: `0 0 0 2px ${state.selected}`,
      boxShadowFocus: `0 0 0 2px ${state.selected}`,
    },
    InternalSelectMenu: {
      optionTextColorActive: accent.onSurface,
      optionTextColorPressed: accent.onSurface,
      optionCheckColor: accent.text,
      optionColorPending: state.hover,
      optionColorActive: state.selected,
      optionColorActivePending: state.selectedHover,
    },
    Dropdown: {
      optionTextColorActive: accent.onSurface,
      optionTextColorChildActive: accent.text,
      optionColorHover: state.hover,
      optionColorActive: state.selected,
    },
    Tabs: {
      tabTextColorActiveLine: accent.text,
      tabTextColorHoverLine: accent.text,
      tabTextColorActiveBar: accent.text,
      tabTextColorHoverBar: accent.text,
      tabTextColorActiveCard: accent.text,
      tabTextColorHoverCard: accent.text,
      tabColorSegment: state.selected,
      tabTextColorActiveSegment: accent.onSurface,
      tabTextColorHoverSegment: accent.text,
      barColor: accent.text,
    },
    Tree: {
      nodeColorHover: state.hover,
      nodeColorPressed: state.pressed,
      nodeColorActive: state.selected,
      dropMarkColor: accent.focus,
    },
    Radio: {
      buttonColorActive: state.selected,
      buttonTextColorActive: accent.onSurface,
      buttonTextColorHover: accent.text,
      buttonBorderColorActive: accent.focus,
      buttonBorderColorHover: accent.borderHover,
      buttonBoxShadowHover: `inset 0 0 0 1px ${accent.borderHover}`,
      buttonBoxShadowFocus: `inset 0 0 0 1px ${accent.focus}, 0 0 0 2px ${state.selected}`,
    },
    Tag: {
      colorPrimary: accent.surface,
      colorBorderedPrimary: accent.surfaceSubtle,
      textColorPrimary: accent.onSurface,
      borderPrimary: `1px solid ${accent.border}`,
      closeIconColorPrimary: accent.text,
      closeIconColorHoverPrimary: accent.text,
      closeIconColorPressedPrimary: accent.text,
      closeColorHoverPrimary: state.selectedHover,
      closeColorPressedPrimary: state.pressed,
      colorInfo: accent.surface,
      colorBorderedInfo: accent.surfaceSubtle,
      textColorInfo: accent.onSurface,
      borderInfo: `1px solid ${accent.border}`,
      closeIconColorInfo: accent.text,
      closeIconColorHoverInfo: accent.text,
      closeIconColorPressedInfo: accent.text,
      closeColorHoverInfo: state.selectedHover,
      closeColorPressedInfo: state.pressed,
    },
    Pagination: {
      itemTextColorHover: accent.text,
      itemTextColorPressed: accent.text,
      itemTextColorActive: accent.onSurface,
      itemColorHover: state.hover,
      itemColorPressed: state.pressed,
      itemColorActive: state.selected,
      itemColorActiveHover: state.selectedHover,
      itemBorderActive: `1px solid ${accent.border}`,
    },
    DatePicker: {
      itemTextColorCurrent: accent.text,
      itemColorIncluded: state.selected,
      itemColorDisabled: theme.surface.muted,
    },
    TimePicker: { itemTextColorActive: accent.text },
    Spin: { color: accent.text, textColor: accent.text },
    Steps: { indicatorTextColorFinish: accent.text },
    Tooltip: {
      borderRadius: '6px',
      boxShadow: theme.shadow.overlay,
      color: theme.surface.raised,
      padding: '7px 10px',
      textColor: theme.text.primary,
    },
    common: {
      actionColor: theme.surface.muted,
      avatarColor: theme.avatar.background,
      baseColor: theme.text.onAccent,
      bodyColor: theme.surface.canvas,
      borderColor: theme.border.strong,
      boxShadow1: theme.shadow.soft,
      boxShadow2: theme.shadow.raised,
      boxShadow3: theme.shadow.overlay,
      buttonColor2: theme.surface.muted,
      buttonColor2Hover: theme.state.hover,
      buttonColor2Pressed: theme.state.pressed,
      cardColor: theme.surface.raised,
      codeColor: theme.surface.muted,
      dividerColor: theme.border.subtle,
      errorColor: theme.status.danger.solid,
      errorColorHover: theme.status.danger.solidHover,
      errorColorPressed: theme.status.danger.solidPressed,
      errorColorSuppl: theme.status.danger.solidHover,
      fontFamily: 'var(--buddy-font-ui)',
      fontFamilyMono: 'var(--buddy-font-mono)',
      hoverColor: theme.state.hover,
      iconColor: theme.text.secondary,
      iconColorDisabled: theme.text.disabled,
      iconColorHover: theme.text.strong,
      iconColorPressed: theme.text.primary,
      infoColor: theme.accent.solid,
      infoColorHover: theme.accent.solidHover,
      infoColorPressed: theme.accent.solidPressed,
      infoColorSuppl: theme.accent.solidHover,
      inputColor: theme.surface.raised,
      inputColorDisabled: theme.surface.muted,
      modalColor: theme.surface.raised,
      placeholderColor: theme.text.secondary,
      placeholderColorDisabled: theme.text.disabled,
      popoverColor: theme.surface.raised,
      pressedColor: theme.state.pressed,
      primaryColor: theme.accent.solid,
      primaryColorHover: theme.accent.solidHover,
      primaryColorPressed: theme.accent.solidPressed,
      primaryColorSuppl: theme.accent.solidHover,
      progressRailColor: theme.border.subtle,
      railColor: theme.border.subtle,
      scrollbarColor: theme.border.strong,
      scrollbarColorHover: theme.text.disabled,
      successColor: theme.status.success.solid,
      successColorHover: theme.status.success.solidHover,
      successColorPressed: theme.status.success.solidPressed,
      successColorSuppl: theme.status.success.solidHover,
      tableColor: theme.surface.raised,
      tableColorHover: theme.state.hover,
      tableColorStriped: theme.surface.muted,
      tableHeaderColor: theme.surface.muted,
      tabColor: theme.surface.canvas,
      tagColor: theme.surface.muted,
      textColor1: theme.text.strong,
      textColor2: theme.text.primary,
      textColor3: theme.text.secondary,
      textColorBase: theme.text.strong,
      textColorDisabled: theme.text.disabled,
      warningColor: theme.status.warning.solid,
      warningColorHover: theme.status.warning.solidHover,
      warningColorPressed: theme.status.warning.solidPressed,
      warningColorSuppl: theme.status.warning.solidHover,
    },
  }
}
