const zh = {
  resizeBoth: '同时调整相邻面板',
  split: '向右分屏',
  splitLeft: '向左分屏',
  splitUp: '向上分屏',
  layout: '面板布局',
  splitDown: '向下分屏',
  merge: '合并分组',
  close: '关闭',
  closeTask: '关闭任务面板',
  closeContext: '关闭上下文页签',
  empty: '从历史打开任务，或新建任务',
  commands: '命令面板',
  commandFailed: '命令未能完成，请重试。',
  searchCommands: '输入命令名称',
  left: '左侧栏',
  right: '右侧栏',
  bottom: '底部面板',
  save: '保存',
  saved: '已保存',
  dirty: '未保存',
  saving: '保存中',
  retry: '重试',
  cancel: '取消',
  discard: '不保存',
  savePrompt: '关闭前保存更改？',
  saveDetail: '未保存的更改仍保留在当前工作副本中。',
  unsentDraftPrompt: '当前任务尚未发送',
  unsentDraftDetail: '当前草稿包含未发送的内容，切换后将丢失。是否在分屏中打开并保留当前草稿？',
  unsentDraftCloseDetail: '当前草稿包含未发送的内容，关闭后将丢失。是否确认放弃？',
  splitOpen: '分屏打开',
  discardDraft: '放弃内容',
  missing: '此视图暂不可用，资源和布局已保留。',
  failed: '视图加载失败。',
  restoreFailed: '工作台恢复失败，请重试。',
  backupFailed: '未保存内容的备份失败。请保存文件或重试备份。',
  conflict: '文件已在外部修改。请比较内容后选择保留的版本。',
  disk: '采用磁盘版本',
  local: '保留我的更改',
  diskVersion: '磁盘版本',
  localVersion: '当前更改',
  files: '文件',
  tasks: '任务',
  settings: '设置',
  automations: '自动化',
  output: '变更',
  browser: '浏览器',
  newTask: '新建任务',
  resize: '调整分组大小',
  preview: '预览',
  source: '源文件',
  readonly: '此文件仅支持预览',
  loading: '正在打开…',
  reveal: '在系统中显示',
  focusNext: '聚焦下一任务面板',
  moveNext: '移动到下一任务面板',
  move: '移动',
  nextTab: '下一个标签',
  previousTab: '上一个标签',
} as const
type Labels = { [K in keyof typeof zh]: string }
const en: Labels = {
  resizeBoth: 'Resize adjacent panes in both directions',
  split: 'Split right',
  splitLeft: 'Split left',
  splitUp: 'Split up',
  layout: 'Pane layout',
  splitDown: 'Split down',
  merge: 'Merge group',
  close: 'Close',
  closeTask: 'Close task pane',
  closeContext: 'Close context tab',
  empty: 'Open a task from history or create a new task',
  commands: 'Command palette',
  commandFailed: 'The command could not be completed. Please retry.',
  searchCommands: 'Search commands',
  left: 'Left sidebar',
  right: 'Right sidebar',
  bottom: 'Bottom panel',
  save: 'Save',
  saved: 'Saved',
  dirty: 'Unsaved',
  saving: 'Saving',
  retry: 'Retry',
  cancel: 'Cancel',
  discard: 'Don’t save',
  savePrompt: 'Save changes before closing?',
  saveDetail: 'Your changes remain in the current working copy.',
  unsentDraftPrompt: 'Current task is unsent',
  unsentDraftDetail: 'The current draft has unsent content which will be lost if you switch. Open in a split pane to keep it?',
  unsentDraftCloseDetail: 'The current draft has unsent content which will be lost if closed. Discard it?',
  splitOpen: 'Open in split',
  discardDraft: 'Discard draft',
  missing: 'This view is unavailable. Its resource and layout have been retained.',
  failed: 'The view could not be loaded.',
  restoreFailed: 'Could not restore the workbench. Please retry.',
  backupFailed: 'Could not back up unsaved changes. Save the file or retry the backup.',
  conflict: 'The file has changed on disk. Compare both versions before choosing which to keep.',
  disk: 'Use disk version',
  local: 'Keep my changes',
  diskVersion: 'Disk version',
  localVersion: 'Your changes',
  files: 'Files',
  tasks: 'Tasks',
  settings: 'Settings',
  automations: 'Automations',
  output: 'Changes',
  browser: 'Browser',
  newTask: 'New task',
  resize: 'Resize group',
  preview: 'Preview',
  source: 'Source',
  readonly: 'This file can only be previewed',
  loading: 'Opening…',
  reveal: 'Show in system',
  focusNext: 'Focus next task pane',
  moveNext: 'Move to next task pane',
  move: 'Move',
  nextTab: 'Next tab',
  previousTab: 'Previous tab',
}
export function workbenchLabels(language: string): Labels {
  return language === 'en-US' ? en : zh
}
