import fs from 'node:fs/promises'
import path from 'node:path'
import { expect, test } from '../fixtures/electron.mjs'

test('builtin working copies back up continued edits, veto closure and recover across restart without executable plugins', async ({ buddy }) => {
  const instance = await buddy.createInstance('working-copy')
  const directory = path.join(instance.home, 'documents')
  const document = path.join(directory, 'README.md')
  await fs.mkdir(directory)
  await fs.writeFile(document, 'Original document.\n')
  let { app, page, diagnostics } = await instance.launch()
  expect(await page.evaluate(async () => (await window.lexoraDesktop.extensions.list()).filter(item => item.manifest.entry || item.manifest.contributes.views.length))).toEqual([])
  await app.evaluate(({ dialog }, directory) => {
    dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [directory] })
  }, directory)
  const section = page.locator('.desktop-task-sidebar__spaces')
  await section.locator('.desktop-task-sidebar__section-heading').hover()
  await section.locator('.desktop-task-sidebar__section-add').click()
  const spaceDialog = page.locator('.desktop-space-dialog')
  await spaceDialog.getByPlaceholder('输入空间名称').fill('工作副本验收')
  await spaceDialog.getByRole('button', { name: '选择目录', exact: true }).click()
  await expect(spaceDialog.locator('.desktop-space-primary-directory input')).toHaveValue(directory)
  await spaceDialog.getByRole('button', { name: '确定', exact: true }).click()
  await expect(spaceDialog).toBeHidden()
  const space = page.locator('.desktop-task-space-row').filter({ hasText: '工作副本验收' })
  await space.hover()
  await space.getByRole('button', { name: '更多操作', exact: true }).click()
  await page.locator('.n-dropdown-menu:visible').getByText('新任务', { exact: true }).click()
  await page.locator('.desktop-workbench-area__tasks .tiptap').click()
  await page.keyboard.press('Control+Shift+P')
  await page.getByPlaceholder('输入命令名称').fill('文件')
  await page.getByPlaceholder('输入命令名称').press('Enter')
  await expect(page.locator('.n-modal')).toBeHidden()
  await page.getByTestId('context-file-tree').getByText('README.md', { exact: true }).click()
  await page.getByTestId('document-mode-edit').click()
  let editor = page.getByTestId('workbench-text-editor')
  await expect(editor.locator('.view-lines')).toContainText('Original document.')
  await editor.locator('.view-lines').click()
  await page.keyboard.press('Control+End')
  await page.keyboard.insertText('First edit.\n')
  await expect(page.locator('.file-editor[data-dirty="true"]')).toBeVisible()
  await page.keyboard.insertText('Second edit while dirty.\n')
  await expect.poll(() => page.evaluate(async () => (await window.lexoraDesktop.workbench.read())?.backups.some(backup => backup.text.includes('Second edit while dirty.')))).toBe(true)
  const readBackup = () => page.evaluate(async () => (await window.lexoraDesktop.workbench.read())?.backups.find(backup => backup.resource.data.path === 'README.md')?.text)
  const beforeUndo = await readBackup()
  await page.keyboard.press('Control+z')
  await expect.poll(readBackup).not.toBe(beforeUndo)
  await page.keyboard.press('Control+y')
  await expect.poll(readBackup).toBe(beforeUndo)
  await expect(editor.locator('.view-lines')).toContainText('Second edit while dirty.')
  expect(await fs.readFile(document, 'utf8')).toBe('Original document.\n')
  await page.getByTestId('task-context-panel').getByRole('button', { name: '关闭文件', exact: true }).click()
  const close = page.locator('.n-dialog').filter({ hasText: '关闭前保存更改？' })
  await close.getByRole('button', { name: '取消', exact: true }).click()
  await expect(close).toBeHidden()
  await expect(editor.locator('.view-lines')).toContainText('Second edit while dirty.')
  await instance.stop()
  ;({ app, page, diagnostics } = await instance.launch())
  const panelToggle = page.getByTestId('context-panel-toggle')
  if (await panelToggle.getAttribute('aria-expanded') === 'false')
    await panelToggle.click()
  editor = page.getByTestId('workbench-text-editor')
  await expect(editor.locator('.view-lines')).toContainText('Second edit while dirty.')
  await expect(page.locator('.file-editor[data-dirty="true"]')).toBeVisible()
  expect(await fs.readFile(document, 'utf8')).toBe('Original document.\n')
  await editor.locator('.view-lines').click()
  await page.keyboard.press('Control+s')
  await expect(page.locator('.file-editor[data-dirty="false"]')).toBeVisible()
  await expect.poll(() => fs.readFile(document, 'utf8')).toContain('Second edit while dirty.')
  await expect.poll(() => page.evaluate(async () => (await window.lexoraDesktop.workbench.read())?.backups.length)).toBe(0)
  expect(diagnostics.console.filter(item => item.type === 'pageerror')).toEqual([])
})

test('task switching stays responsive during loading, failure and notification navigation', async ({ buddy }) => {
  const instance = await buddy.createInstance('task-switch')
  const { app, page, diagnostics } = await instance.launch()
  await app.evaluate((_electron, databasePath) => {
    const { DatabaseSync } = process.getBuiltinModule('node:sqlite')
    const db = new DatabaseSync(databasePath)
    try {
      const now = new Date().toISOString()
      for (const id of ['a', 'b', 'c']) {
        db.prepare('INSERT INTO conversations (id, title, active_branch_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?)').run(id, `Task ${id.toUpperCase()}`, `branch-${id}`, now, now)
        db.prepare('INSERT INTO conversation_branches (id, conversation_id, created_at) VALUES (?, ?, ?)').run(`branch-${id}`, id, now)
        db.prepare('INSERT INTO messages (id, conversation_id, branch_id, role, content_json, created_at) VALUES (?, ?, ?, ?, ?, ?)').run(`message-${id}`, id, `branch-${id}`, 'user', JSON.stringify({ text: `Content ${id.toUpperCase()}` }), now)
      }
      db.prepare('INSERT INTO conversation_branches (id, conversation_id, created_at) VALUES (?, ?, ?)').run('notified-branch', 'b', now)
      db.prepare('INSERT INTO messages (id, conversation_id, branch_id, role, content_json, created_at) VALUES (?, ?, ?, ?, ?, ?)').run('notified-message', 'b', 'notified-branch', 'user', JSON.stringify({ text: 'Notification target content' }), now)
      db.prepare('INSERT INTO runs (id, conversation_id, branch_id, triggering_message_id, provider, model, purpose, status, started_at, completed_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').run('notified-run', 'b', 'notified-branch', 'notified-message', 'fixture', 'fixture', 'chat', 'completed', now, now)
    }
    finally { db.close() }
  }, path.join(instance.home, 'buddy/buddy.sqlite3'))
  await page.reload()
  const row = id => page.locator(`[data-task-id="${id}"] .desktop-task-sidebar__task`)
  const editor = page.locator('.desktop-chat-composer__prosemirror:visible')
  const title = page.locator('.workbench-pane-title:visible')
  await row('a').click()
  await expect(editor).toBeVisible()
  await editor.fill('Saved while switching')
  await app.evaluate(({ ipcMain }) => {
    const probe = globalThis.taskSwitchProbe = { events: [], gates: new Map(), fail: null }
    for (const [stage, channel] of [
      ['get', 'lexora:buddy:conversations:get'],
      ['draft', 'lexora:buddy:composer-drafts:open'],
      ['branches', 'lexora:buddy:conversations:list-branches'],
      ['timeline', 'lexora:buddy:conversations:list-timeline'],
    ]) {
      const handler = ipcMain._invokeHandlers.get(channel)
      ipcMain.removeHandler(channel)
      ipcMain.handle(channel, async (event, input) => {
        const id = input.conversationId ?? input.scope?.conversationId
        probe.events.push({ id, stage, phase: 'start' })
        await probe.gates.get(`${stage}:${id}`)?.promise
        if (stage === 'get' && probe.fail === id)
          throw new Error('Isolated task read failure')
        const result = await handler(event, input)
        probe.events.push({ id, stage, phase: 'end' })
        return result
      })
    }
  })
  const block = key => app.evaluate((_electron, key) => {
    globalThis.taskSwitchProbe.gates.set(key, Promise.withResolvers())
  }, key)
  const release = key => app.evaluate((_electron, key) => {
    const gates = globalThis.taskSwitchProbe.gates
    gates.get(key)?.resolve()
    gates.delete(key)
  }, key)
  await block('draft:b')
  await row('b').click()
  await expect(title).toHaveText('Task B')
  await expect(row('b')).toHaveClass(/is-active/)
  await expect(page.getByTestId('task-loading')).toHaveAttribute('aria-busy', 'true')
  await expect.poll(() => app.evaluate(() => globalThis.taskSwitchProbe.events.some(event => event.id === 'b' && event.stage === 'timeline' && event.phase === 'end'))).toBe(true)
  expect(await app.evaluate(() => globalThis.taskSwitchProbe.events.some(event => event.id === 'b' && event.stage === 'draft' && event.phase === 'end'))).toBe(false)
  await row('c').click()
  await expect(title).toHaveText('Task C')
  await expect(editor).toBeVisible()
  await release('draft:b')
  await expect.poll(() => app.evaluate(() => globalThis.taskSwitchProbe.events.some(event => event.id === 'b' && event.stage === 'draft' && event.phase === 'end'))).toBe(true)
  await expect(title).toHaveText('Task C')
  await row('a').click()
  await expect(editor).toHaveText('Saved while switching')

  await app.evaluate(() => {
    globalThis.taskSwitchProbe.fail = 'b'
  })
  await row('b').click()
  const failed = page.getByTestId('task-loading').getByRole('alert')
  await expect(failed).toContainText('视图加载失败')
  await row('a').click()
  await expect(editor).toHaveText('Saved while switching')
  await row('b').click()
  await expect(failed).toBeVisible()
  await app.evaluate(() => {
    globalThis.taskSwitchProbe.fail = null
  })
  await failed.getByRole('button', { name: '重试', exact: true }).click()
  await expect(editor).toBeVisible()
  await expect(page.getByTestId('task-loading')).toHaveCount(0)

  await row('a').click()
  await expect(editor).toHaveText('Saved while switching')
  await block('get:b')
  await app.evaluate(({ BrowserWindow }) => {
    BrowserWindow.getAllWindows()[0].webContents.send('lexora:app:open-target', { conversationId: 'b', runId: 'notified-run' })
  })
  await expect(title).toHaveText('Task B')
  await expect(page.getByTestId('task-loading')).toBeVisible()
  await release('get:b')
  await expect.poll(() => page.evaluate(async () => (await window.lexoraDesktop.localChat.conversations.get('b')).activeBranchId)).toBe('notified-branch')
  await expect(page.locator('.desktop-chat-page')).toContainText('Notification target content')
  expect(diagnostics.console.filter(item => item.type === 'pageerror')).toEqual([])
})

test('sidebar resizing and collapsing preserve the current draft and persist whole-pixel widths', async ({ buddy }) => {
  const instance = await buddy.createInstance('sidebar-layout')
  const { page, diagnostics } = await instance.launch()
  const editor = page.locator('.desktop-chat-composer__prosemirror:visible')
  await editor.fill('Keep this draft while changing the layout.')
  const sidebar = page.locator('.desktop-workbench-layout__sidebar')
  const resize = page.getByTestId('workbench-sidebar-resizer')
  const width = () => sidebar.evaluate(async (element) => {
    await Promise.all(element.getAnimations().map(animation => animation.finished))
    return element.getBoundingClientRect().width
  })
  const initialWidth = await width()
  await resize.focus()
  await page.keyboard.press('ArrowRight')
  await expect.poll(width).toBeGreaterThan(initialWidth)
  const beforeDrag = await width()
  const handle = await resize.boundingBox()
  await page.mouse.move(handle.x + handle.width / 2, handle.y + 80)
  await page.mouse.down()
  await page.mouse.move(handle.x + 40.375, handle.y + 80.25, { steps: 5 })
  await page.mouse.up()
  await expect.poll(width).toBeGreaterThan(beforeDrag)
  const expandedWidth = await width()
  const savedWidth = () => page.evaluate(async () => (await window.lexoraDesktop.settings.get()).desktop.taskSidebar.width)
  await expect.poll(savedWidth).toBe(Math.round(expandedWidth))

  const toggle = page.getByTestId('workbench-sidebar-toggle')
  await resize.hover()
  await toggle.click()
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await expect.poll(width).toBe(0)
  await expect(sidebar).toHaveAttribute('inert', '')
  await expect(editor).toHaveText('Keep this draft while changing the layout.')
  await page.locator('.desktop-workbench-layout__sidebar-collapsed-boundary').hover()
  await toggle.click()
  await expect(toggle).toHaveAttribute('aria-expanded', 'true')
  await expect.poll(width).toBeCloseTo(expandedWidth, 0)
  await expect(editor).toHaveText('Keep this draft while changing the layout.')
  await instance.stop()
  const restarted = await instance.launch()
  await expect.poll(() => restarted.page.evaluate(async () => (await window.lexoraDesktop.settings.get()).desktop.taskSidebar.width)).toBe(Math.round(expandedWidth))
  await expect(restarted.page.locator('.desktop-chat-composer__prosemirror:visible')).toHaveText('Keep this draft while changing the layout.')
  expect(diagnostics.console.filter(item => item.type === 'pageerror')).toEqual([])
})
