import fs from 'node:fs/promises'
import path from 'node:path'
import { expect, test } from '../fixtures/electron.mjs'

test('builtin working copies back up continued edits, veto closure and recover across restart without plugins', async ({ buddy }) => {
  const instance = await buddy.createInstance('working-copy')
  const directory = path.join(instance.home, 'documents')
  const document = path.join(directory, 'README.md')
  await fs.mkdir(directory)
  await fs.writeFile(document, 'Original document.\n')
  let { app, page, diagnostics } = await instance.launch()
  expect(await page.evaluate(() => window.lexoraDesktop.extensions.list())).toEqual([])
  await app.evaluate(({ dialog }, directory) => {
    dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [directory] })
  }, directory)
  const section = page.locator('.desktop-task-sidebar__spaces')
  await section.locator('.desktop-task-sidebar__section-heading').hover()
  await section.locator('.desktop-task-sidebar__section-add').click()
  const spaceDialog = page.locator('.desktop-space-dialog')
  await spaceDialog.getByPlaceholder('输入空间名称').fill('工作副本验收')
  await spaceDialog.getByRole('button', { name: '选择目录', exact: true }).click()
  await expect(spaceDialog.locator('.desktop-space-primary-directory input')).toHaveValue(directory)
  await spaceDialog.getByRole('button', { name: '确定', exact: true }).click()
  await expect(spaceDialog).toBeHidden()
  const space = page.locator('.desktop-task-space-row').filter({ hasText: '工作副本验收' })
  await space.hover()
  await space.getByRole('button', { name: '更多操作', exact: true }).click()
  await page.locator('.n-dropdown-menu:visible').getByText('新任务', { exact: true }).click()
  await page.locator('.desktop-workbench-area__tasks .tiptap').click()
  await page.keyboard.press('Control+Shift+P')
  await page.getByPlaceholder('输入命令名称').fill('文件')
  await page.getByPlaceholder('输入命令名称').press('Enter')
  await expect(page.locator('.n-modal')).toBeHidden()
  await page.getByTestId('context-file-tree').getByText('README.md', { exact: true }).click()
  await page.getByTestId('document-mode-edit').click()
  let editor = page.getByTestId('workbench-text-editor')
  await expect(editor.locator('.view-lines')).toContainText('Original document.')
  await editor.locator('.view-lines').click()
  await page.keyboard.press('Control+End')
  await page.keyboard.insertText('First edit.\n')
  await expect(page.locator('.file-editor[data-dirty="true"]')).toBeVisible()
  await page.keyboard.insertText('Second edit while dirty.\n')
  await expect.poll(() => page.evaluate(async () => (await window.lexoraDesktop.workbench.read())?.backups.some(backup => backup.text.includes('Second edit while dirty.')))).toBe(true)
  await expect.poll(() => page.evaluate(async () => Object.values((await window.lexoraDesktop.workbench.read())?.layout.views ?? {}).some(view => view.type === 'files.editor' && view.state.editor?.cursorState?.[0]?.position.lineNumber === 4))).toBe(true)
  const readBackup = () => page.evaluate(async () => (await window.lexoraDesktop.workbench.read())?.backups.find(backup => backup.resource.data.path === 'README.md')?.text)
  const beforeUndo = await readBackup()
  await page.keyboard.press('Control+z')
  await expect.poll(readBackup).not.toBe(beforeUndo)
  await page.keyboard.press('Control+y')
  await expect.poll(readBackup).toBe(beforeUndo)
  await expect(editor.locator('.view-lines')).toContainText('Second edit while dirty.')
  expect(await fs.readFile(document, 'utf8')).toBe('Original document.\n')
  await page.getByTestId('task-context-panel').getByRole('button', { name: '关闭文件', exact: true }).click()
  const close = page.locator('.n-dialog').filter({ hasText: '关闭前保存更改？' })
  await close.getByRole('button', { name: '取消', exact: true }).click()
  await expect(close).toBeHidden()
  await expect(editor.locator('.view-lines')).toContainText('Second edit while dirty.')
  await instance.stop()
  ;({ app, page, diagnostics } = await instance.launch())
  const panelToggle = page.getByTestId('context-panel-toggle')
  if (await panelToggle.getAttribute('aria-expanded') === 'false')
    await panelToggle.click()
  editor = page.getByTestId('workbench-text-editor')
  await expect(editor.locator('.view-lines')).toContainText('Second edit while dirty.')
  await expect(page.locator('.file-editor[data-dirty="true"]')).toBeVisible()
  expect(await fs.readFile(document, 'utf8')).toBe('Original document.\n')
  await editor.locator('.view-lines').click()
  await page.keyboard.press('Control+s')
  await expect(page.locator('.file-editor[data-dirty="false"]')).toBeVisible()
  await expect.poll(() => fs.readFile(document, 'utf8')).toContain('Second edit while dirty.')
  await expect.poll(() => page.evaluate(async () => (await window.lexoraDesktop.workbench.read())?.backups.length)).toBe(0)
  await page.screenshot({ path: path.join(instance.artifactDirectory, 'recovered-and-saved.png'), animations: 'disabled' })
  expect(diagnostics.console.filter(item => item.type === 'pageerror')).toEqual([])
})
